version: '3.8'

services:
  web:
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_JWT_SECRET=${NEXTAUTH_JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo
    ports:
      - 2717:27017
    volumes:
      - amazona:/data/db

volumes:
  amazona:
