import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import { Providers } from './providers'
import ToastComponent from './components/toaster/ToastComponent'
import Header from './components/header/Header'
import Footer from './components/footer/Footer'
import Home from './components/initial/Initial'
import { getServerSession } from 'next-auth'
import { authOptions } from "@/app/utils/authOptions"
import HeaderAdmin from './components/admin/header/HeaderAdmin'
import { PrismaClient } from "@prisma/client";
import { fetchCategory } from "@/actions/actions";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({children}) => {
  const prisma = new PrismaClient();
  const categoriesData = await fetchCategory();
  const session = await getServerSession(authOptions);
  if (session?.user?.role === "ADMIN") {
     return (
      <html lang="en">
      <body className={inter.className}>
        <Providers>
         <HeaderAdmin />
        {children}
      
        <ToastComponent />
        </Providers>
      </body>
    </html>    
     )
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
       <Header categoriesData={categoriesData}/>
        {children}
        <Footer />
        <ToastComponent />
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout